const mongoose = require('mongoose')
const Schema = mongoose.Schema

const WilderSchema = new Schema(
  {
    name: {
      type: String,
      unique: true,
      // This is an error generated by Mongoose but that's not very good cause we need to pass in the schema to the model
      required: [true, 'The name is required'],
    },
    city: String,
    skills: [
      {
        title: String,
        votes: Number,
      },
    ],
  },
  {
    versionKey: false,
  }
)

module.exports = mongoose.model('Wilder', WilderSchema)